[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo = "3ocSjQ5wcn1BobyoWs26guVuZ8J1QTvBhPaacKp4Zqem"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
